test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.990d0ae6d5c98db4de9342bb19e3797c9df0da73.name = "Upgrade from 4.16.0"