#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

# this will most likely adjust NGINX config correctly
ynh_config_change_url_nginx

#=================================================
# RECONFIGURING MATOMO
#=================================================
ynh_script_progression "Reconfiguring Matomo..."

ynh_replace --match="$old_domain" --replace="$new_domain" --file="$install_dir/config/config.ini.php"

#=================================================
# SETUP A CRON
#=================================================
ynh_script_progression "Setuping a cron..."

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
